---
output:
  pdf_document: default
  html_document: default
---
# Andmeanalüüs

Andmeanalüüsi tegin mina, peacecop kalmer:, üksi. Kui arvutustulemuste koht on kas tabelis *\@ref(tab:comparing-theoretical-forces-to-actual-applied-to-same-point)* või *\@ref(tab:parallel-forces)*, siis need arvutused on näidatud vahetult enne vastavat tabelit.

Andmeanalüüs esimese praktilise osa kohta:

1. Arvutasin raskusjõu ehk tasakaalustava jõu $P = m \cdot g$ (raskuse kaalu) arvväärtuse ja kandsin selle tabelisse *\@ref(tab:comparing-theoretical-forces-to-actual-applied-to-same-point)*.

2. Valisin sobiva mastaabi $1 \cdot 10^{-2} \cdot m = 1 N$ ja kandsin joonisele *\@ref(fig:adding-forces-1)* õige pikkusega lõigud (vektorite $\overrightarrow{F}$, $\overrightarrow{Q}$, $\overrightarrow{P}$) pikkused, mis vastavad dünamomeetri näidule. Kirjutasin juurde mastaabi, st mitu pikkusühikut olen võtnud vastavaks ühele njuutonile.

3. Konstrueerisin vektoritele $\overrightarrow{F}$ ja $\overrightarrow{Q}$ rööpküliku. Kuigi juhendis on kirjas, et seda tuleb teha joonlaua ja sirkli abil, kasutasin ma kaasaegset vahendit, mille nimi on GeoGebra [@geogebra]. Jah, ma oskan konstrueerida rööpkülikut nii kahe joonlaua kui sirkli ja joonlauaga, aga niiviisi konstrueerimise tulemus ei ole reprodutseeritav, kuigi nii saab konstrueerida nt looduses.

4. Lasin röökülikule joonestada pikema diagonaali *R*.

5. Võtsin GeoGebra jooniselt diagonaali *R* (resultantjõu) pikkuse ja kirjutasin selle väärtuse *10.2* $R_{eksp}$ tabelisse \@ref(tab:comparing-theoretical-forces-to-actual-applied-to-same-point).

6. Lasin arvutada resultantjõu teoreetilise väärtuse $R_{teor}$ vastavalt valemile *\@ref(eq:cosine-theorem)* ja tulemuse tabelisse \@ref(tab:comparing-theoretical-forces-to-actual-applied-to-same-point) kanda.

7. Lasin arvutada jõudude $R_{eksp}$ ja $R_{teor}$ suhtelise erinevuse $R_r = \frac{|R_{eksp} - R_{teor}|}{R_{teor}}$ ja tulemuse tabelisse \@ref(tab:comparing-theoretical-forces-to-actual-applied-to-same-point) kanda.

8. Võrdlesin resultantjõu suurust tasakaalustava jõuga (raskuse kaaluga).

9. Lasin arvutada resultantjõu $R_{eksp}$ ja tasakaalustava jõu (raskuse kaaluga) *P* suhtelise erinevuse $R_{RP} = \frac{|R_{eksp} - P|}{R_{eksp}}$ ja tulemuse tabelisse \@ref(tab:comparing-theoretical-forces-to-actual-applied-to-same-point) kanda.

```{=tex}
\begin{figure}
\begin{tikzpicture}[line cap=round,line join=round,>=triangle 45,x=1cm,y=1cm]
\begin{axis}[
x=1cm,y=1cm,
axis lines=middle,
ymajorgrids=true,
xmajorgrids=true,
xmin=-4.448369560180092,
xmax=9.148475046770661,
ymin=-10.07662339842799,
ymax=13.444828113324013,
xtick={-4,-2,...,8},
ytick={-10,-8,...,12},
\axispapermm]
\clip(-4.448369560180092,-10.07662339842799) rectangle (9.148475046770661,13.444828113324013);
\fill[line width=2pt,color=zzttqq,fill=zzttqq,fill opacity=0.10000000149011612] (0,0) -- (2.4721359549995796,7.608452130361228) -- (-0.592041817476332,10.179602569107386) -- (-3.0641777724759116,2.571150438746158) -- cycle;
\draw [->,line width=2pt] (0,0) -- (0,-9.8182);
\draw [->,line width=2pt] (0,0) -- (2.4721359549995796,7.608452130361228);
\draw [->,line width=2pt] (0,0) -- (-3.0641777724759116,2.571150438746158);
\draw [->,line width=2pt] (-3.0641777724759116,2.571150438746158) -- (-0.592041817476332,10.179602569107386);
\draw [line width=2pt,color=zzttqq] (0,0)-- (2.4721359549995796,7.608452130361228);
\draw [line width=2pt,color=zzttqq] (2.4721359549995796,7.608452130361228)-- (-0.592041817476332,10.179602569107386);
\draw [line width=2pt,color=zzttqq] (-0.592041817476332,10.179602569107386)-- (-3.0641777724759116,2.571150438746158);
\draw [line width=2pt,color=zzttqq] (-3.0641777724759116,2.571150438746158)-- (0,0);
\draw [line width=2pt] (0,0)-- (-0.592041817476332,10.179602569107386);
\begin{scriptsize}
\draw [fill=ududff] (0,0) circle (2.5pt);
\draw[color=ududff] (0.3105260522526718,0.8546729628492933) node {$O$};
\draw [fill=ududff] (0,-9.8182) circle (2.5pt);
\draw[color=ududff] (0.3105260522526718,-8.976891599099813) node {$C$};
\draw[color=black] (4.07580609725442,-4.296439320937871) node {$\overrightarrow{P}$};
\draw[color=black] (5.0955694427757265,4.436918561219047) node {$\overrightarrow{Q}$};
\draw [fill=uuuuuu] (2.4721359549995796,7.608452130361228) circle (2pt);
\draw[color=uuuuuu] (2.7945649708302134,8.411380830943154) node {$B$};
\draw[color=black] (-2.3500527432952856,1) node {$\overrightarrow{F}$};
\draw [fill=uuuuuu] (-3.0641777724759116,2.571150438746158) circle (2pt);
\draw[color=uuuuuu] (-2.748763984311248,3.3648596595171503) node {$A$};
\draw [fill=uuuuuu] (-0.592041817476332,10.179602569107386) circle (2pt);
\draw[color=uuuuuu] (-0.29087284382399614,10.97386308379159) node {$D$};
\draw[color=black] (0,5.718159687643265) node {$R = 10.2$};
\end{scriptsize}
\end{axis}
\end{tikzpicture}
  \caption{Esimese katse jõuvektorid} \label{fig:adding-forces-1}
  \end{figure}
```
