# Mõõtmistulemused

```{r comparing-theoretical-forces-to-actual-applied-to-same-point, attr.source = ".numberLines"}
columns = c(
  "Katse nr.",
  "$m$ [kg]",
  "$F$ [N]",
  "$Q$ [N]",
  "$\\alpha$ [°]",
  "$R_{eksp}$ [N]",
  "$R_{teor}$ [N]",
  "$P$ [N]",
  "Jõudude $R_{eksp}$ ja $R_{teor}$ suhteline erinevus",
  "Jõudude $R_{eksp}$ ja $P$ suhteline erinevus"
)
id <- c(paste(1:2, ".", sep = ""))
m <- c(1, 2)
f <- c(4, 8)
q <- c(8, 16)
alpha <- c(68, 59)
r_eksp <- c("", "")
r_teor <- c('', '')
p <- c('', '')
relative_difference_r_eksp_r_teor = c('', '')
relative_difference_r_eksp_p = c("", "")
same_point_different_lines <- data.frame(
  "id" <-  id,
  "m" <- m,
  "f" <- f,
  "q" <- q,
  "alpha" <- alpha,
  "r_eksp" <- r_eksp,
  "r_teor" <- r_teor,
  "p" <- p,
  "relative_difference_r_eksp_r_teor" <- relative_difference_r_eksp_r_teor,
  "relative_difference_r_eksp_p" <- relative_difference_r_eksp_p
)
if (knitr::opts_knit$get('rmarkdown.pandoc.to') == "docx") {
  library(flextable)
  flextable(same_point_different_lines)
} else {
  library(kableExtra)
  saveRDS(object = same_point_different_lines, "determining.rds")
  colnames(same_point_different_lines) <- columns
  kable(
    same_point_different_lines,
    format = "latex",
    booktabs = TRUE,
    escape = FALSE,
    caption = "Samas punktis rakendatud erisihiliste vektorite katse andmed",
    digits = 24
  ) %>% kable_styling(
    bootstrap_options = c("striped", "bordered", "condensed", "responsive", "hover"),
    latex_options = "scale_down",
    full_width = TRUE
  ) %>% column_spec(1, width = "1cm") %>% column_spec(9, width = "2cm") %>% column_spec(10, width = "2cm")
}
```


```{r parallel-forces, attr.source = ".numberLines"}
columns = c(
  "Katse nr.",
  "$m_1$ [kg]",
  "$m_2$ [kg]",
  "$F$ [N]",
  "$Q$ [N]",
  "$AM$ [cm]",
  "$BM$ [cm]",
  "$\\frac{Q}{F}$",
  "$\\frac{AM}{BM}$",
  "$\\frac{Q}{F} - \\frac{AM}{BM}$"
)
id <- c(paste(1:2, ".", sep = ""))
m_1 <- c(1, .5)
m_2 <- c(3.0012, 5)
f <- c(12, 12)
q <- c(26, 42)
am <- c(17.3, 27.1)
bm <- c(9.8, 2.3)
q_over_f <- c('', '')
am_over_bm <- c('', '')
difference_q_over_f_and_am_over_bm = c('', '')
parallel_forces <- data.frame(
  "id" <-  id,
  "m_1" <- m_1,
  "m_2" <- m_2,
  "f" <- f,
  "q" <- q,
  "am" <- am,
  "bm" <- bm,
  "q_over_f" <- q_over_f,
  "am_over_bm" <- am_over_bm,
  "difference_q_over_f_and_am_over_bm" <- difference_q_over_f_and_am_over_bm
)
if (knitr::opts_knit$get('rmarkdown.pandoc.to') == "docx") {
  library(flextable)
  flextable(parallel_forces)
} else {
  library(kableExtra)
  saveRDS(object = parallel_forces, "determining.rds")
  colnames(parallel_forces) <- columns
  kable(
    parallel_forces,
    format = "latex",
    booktabs = TRUE,
    escape = FALSE,
    caption = "Rööpsete jõudude katseandmed",
    digits = 24
  ) %>% kable_styling(
    bootstrap_options = c("striped", "bordered", "condensed", "responsive", "hover"),
    latex_options = "scale_down",
    full_width = TRUE
  ) %>% column_spec(1, width = "1cm") %>% column_spec(9, width = "2cm") %>% column_spec(10, width = "2cm")
}
```
